### ISSUE TITLE
useless output on a waveformfile 

### ISSUE THREAD

**Issue by jonardan** [fread-ink/inkwave#14]
Hello, I'm not sure if i should post this as an issue but i tried to use the script for a waveform file i have and it seems to me that it is not working properly, it recognizes the 3 modes present in the file but as an output I get this
{"mode": 2, "ranges": [{"index": 0, "phases": [[[]
},{"index": 1, "phases": [[[]
},{"index": 2, "phases": [[[]
},{"index": 3, "phases": [[[]
},{"index": 4, "phases": [[[]
},{"index": 5, "phases": [[[]

for any index and any mode, i don't know if it is the expected output but it seems to me that there is no useful information in this kind of output and i cannot understand why is that ( could it be that the file uses a big-endian architecture? i don't know how to check) , could you help me?

**Comment by Juul** [comment]
Are you able to share the waveform file or is it proprietary? I don't think I'll be able to help you without it

**Comment by jonardan** [comment]
it is proprietary, if you want we can continue by mail, j.sciaky@libero.it

**Comment by Juul** [comment]
Ah I'm sorry. You're on your own then unfortunately
